name: Frecuencia Discord

on:
  schedule:
    - cron: '0 4 * * *'   # Todos los días a las 04:00 UTC
  workflow_dispatch:

jobs:
  enviar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
        run: python main.py
